safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'LICENSE']
baseurl: /nyc-subway-anthrax-study
imports:
    - https://peerj.github.io/research-article/research-article.html
theme: https://peerj.github.io/research-article/components/
collections:
    figures:
        output: true
        title: 'Figures'
    tables:
        output: true
        title: 'Tables'
    sections:
        output: true

markdown: kramdown
kramdown:
  input: GFM

gitrepo: "https://github.com/Read-Lab-Confederation/nyc-subway-anthrax-study/blob/gh-pages/"
